file_format: "1"
id: supermini_split
name: Supermini Split Keyboard
type: shield
url: https://example.com/supermini-split
requires:
  - nrf52840
exposes: []
features:
  - keys
  # underglow # Include this only if your keyboard supports RGB underglow.
  # - encoder  # Uncomment if your keyboard includes rotary encoders.
  # - display  # Uncomment if your keyboard has an OLED or other display.
siblings:
  - supermini_split_left
  - supermini_split_right
